### ISSUE TITLE
Why the for takes the last IP of the array?

### ISSUE THREAD

**Issue by rtorrescodes** [masbung/GOpen#3]
answer me !!

**Comment by eocampo** [comment]
@rodrigotorres79 Thank you for raising up this issue. I think that you are talking about the `SynchronousSocketListener` class, are you?

If it's the case I you are talking about this code:
```CSharp
 for (int i = 0; i < ipHostInfo.AddressList.LongLength; i++) {
   if (ipHostInfo.AddressList[i].AddressFamily == AddressFamily.InterNetwork)
     ipAddress = ipHostInfo.AddressList[i];
 }
```

It's a real bug, the for loop continues even when the correct Address is already found and assigned. To fix it we'll need to add a break to exit the loop.

https://github.com/masbung/GOpen/blob/master/src/Sandbox/eocampo/EOPenServer/SynchronousSocketListener.cs#L25

I'll correct the Bug and let you know.

Note: When you are raising a bug like Issue please add the bug Label.

**Comment by rtorrescodes** [comment]
Ok thanks :( go on, fix it soon please !
